name: JEMS Github Actions Deploy CICD
run-name: Deploying main.
on: [push]
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Kill Node Servers and git pull
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DIGITALOCEAN_SSH_HOST }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          script: |
            cd JEMS
            git pull
            killall node
            touch test.ts

  Deploy-Backend:
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Build-And-Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DIGITALOCEAN_SSH_HOST }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          script: |
            cd JEMS/server
            touch test2.ts
            npm install
            node server.ts
