name: JEMS Github Actions Deploy CICD
run-name: Deploying main.
on: [push]
jobs:
  Setup-and-ssh:
    runs-on: ubuntu-latest
    steps:


      - name: Install SSH key of bastion
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          name: id_rsa-github-actions-droplet
          known_hosts: ${{ secrets.DIGITALOCEAN_SSH_HOST }}

      - name: ssh into jems-droplet
        run: ssh root@${{ secrets.DIGTALOCEAN_SSH_HOST }}

      - name: navigate to directory
        run: cd JEMS/server

      - name: testing repo
        run: touch test.ts

  Build:
    needs: Setup-and-ssh
    runs-on: ubuntu-latest
    steps:
      - name: testing position and place
        run: touch test2.ts
