name: JEMS Github Actions Deploy CICD
run-name: Deploying main.
on: [push]
jobs:
  Setup-and-ssh:
    runs-on: ubuntu-latest
    steps:


      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DIGITALOCEAN_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: ssh into jems-droplet
        run: ssh root@${{ secrets.DIGITALOCEAN_SSH_HOST }}

      - name: navigate to directory
        run: cd JEMS/server

      - name: testing repo
        run: touch test.ts

  Build:
    needs: Setup-and-ssh
    runs-on: ubuntu-latest
    steps:
      - name: testing position and place
        run: touch test2.ts
