name: Test Node js

on: [push]

jobs:
  TestBackend:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./server/

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: "latest"
    
    - name: npm Clean Install
      run: npm ci
    - name: Run build
      run: npm run build --if-present

    - name: Run Tests
      run: |
        echo 'MONGO_DB_CONNECTION_STRING="mongodb://127.0.0.1:27017"' > .env
        npm run test

    - name: break down mongodb
      run: |
        docker stop mongodb
        docker rm mongodb

  
    
  TestCypress:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Prepare client directory for npm start
      run: npm ci
      working-directory: ./client/

    - name: init npm for cypress install in JEMS directory
      run: npm init -y
    - name: Cypress install in JEMS directory
      run: |
        npm install typescript
        npm install cypress

    - name: Link cypress for testing client directory
      uses: cypress-io/github-action@v6
      with:
        runTests: false

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        install: false
        project: ./client/
        start: npm start --prefix ./client/
        browser: chrome
