name: Test Node js

on: [push]

jobs:
  TestBackend:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./server/

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm Clean Install
      run: npm ci
    - name: Run build
      run: npm run build --if-present

    - name: Run Tests
      run: npm run test
        
  TestCypress:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./client/

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm Clean Install
      run: npm ci
    - name: Run build
      run: npm run build --if-present
    - name: run start
      run: npm start

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        install: false
        project: ./client/
        browser: chrome
